### ISSUE TITLE
Add to F-Droid main repository

### ISSUE THREAD

**Issue by EchedeyLR** [krawieck/lemmur#112]
How to: https://f-droid.org/en/docs/Inclusion_How-To/
Policy: https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by shilangyu** [comment]
Thanks for opening an issue about it. It's in our plans. We hope to do it soon.

**Comment by fossdd** [comment]
We are on, i've opened a [PR](https://github.com/krawieck/lemmur/pull/132) that initalize the fastlane structures for metadata like descriptions and screenshots.

You don't setup the `versionCode` in your `pubspec.yaml`, nice if you can append `+<number>`. And increment that with every release.

https://github.com/krawieck/lemmur/blob/v0.2.2/pubspec.yaml#L18

**Comment by EchedeyLR** [comment]
Done: https://f-droid.org/packages/com.krawieck.lemmur

I think this can be closed already.

**Comment by shilangyu** [comment]
This still leads to a 404, we are waiting for f-droid to publish lemmur (it was already built by their system)

**Comment by EchedeyLR** [comment]
El 15 de febrero de 2021 9:53:48 WET, Marcin Wojnarowski <notifications@github.com> escribió:
>This still leads to a 404, we are waiting for f-droid to publish lemmur (it was already built by their system)
>

Oh, so even when I can download it from F-Droid app, is not added in their website?
-- 
Saludos,
Echedey, López Romero

**Comment by shilangyu** [comment]
Oh, you're right! It is indeed on f-droid but not on the website, I have not noticed. That's exciting, sorry for reopening then!
