### ISSUE TITLE
www.chapo.chat fails to login

### ISSUE THREAD

**Issue by zyphlar** [krawieck/lemmur#114]
### Device info

- OS: Android
- OS version: idk
- Device: Samsung

### Steps to reproduce

1. Add either www.chapo.chat or chapo.chat to instances
2. Try to login to instance
3. See raw 301 redirect response instead of success or useful error

### Expected behavior

I can login

### Screenshots/Screencasts

https://imgur.com/a/YgVkh2c

**Comment by SirLotsaLocks** [comment]
I believe this has to do with chapo.chat's different captcha (hcaptcha)

**Comment by krawieck** [comment]
Thanks, we are aware of it. We'll see what we can do about that after we switch to API v2

**Comment by krawieck** [comment]
Closing it since ~chapo.chat~ hexbear.net seem to be more interested in developing their own fork instead of the latest lemmy version
