### ISSUE TITLE
App not installed issue on Poco F1

### ISSUE THREAD

**Issue by suvo-lib** [krawieck/lemmur#115]
### Device info

- OS: Android
- OS version: 10
- Device: Poco F1

### Describe the bug
After downloading the .apk from the GitHub page, if I try to install it (after allowing the install of .apk from settings) a dialog box appears which says `App Not Installed`.

### Screenshots/Screencasts
![IMG_20210117_104628](https://user-images.githubusercontent.com/72407863/104831719-73315280-58b1-11eb-8a4a-1ad929cfa3ae.jpg)

**Comment by kazukyakayashi** [comment]
Same here

## Device info

- OnePlus 6T
- OS : Android 10

**Comment by shilangyu** [comment]
This is a weird behavior I have noticed myself when trying to install other APKs as well. To fix this, one of the following steps should work for you:

- Make sure that the app you used to install the apk has permissions to "install unknown apps"
- Use a different app to install the apk: for example a different file manager


If none of these work, let me know and I'll investigate it further

**Comment by suvo-lib** [comment]
> This is a weird behavior I have noticed myself when trying to install other APKs as well. To fix this, one of the following steps should work for you:
> 
> * Make sure that the app you used to install the apk has permissions to "install unknown apps"
> * Use a different app to install the apk: for example a different file manager
> 
> If none of these work, let me know and I'll investigate it further

None of them worked.

**Comment by suvo-lib** [comment]
Okay, so I've been trying to install using the `x86_64` version. A comrade told me to use the arm version (the first one in the Asset list), and I did. It has been installed. 👍🏼
