### ISSUE TITLE
Can't log in to lemmy.ml: LemmyApiException:

### ISSUE THREAD

**Issue by michel-slm** [krawieck/lemmur#119]
### Device info

- OS: Android
- OS version: 11
- Device: Pixel 3

### Describe the bug
I can't login with my `lemmy.ml` account (that I have had since the `dev.lemmy.ml` days). I verified and the same credentials work fine on Firefox.

### Steps to reproduce

1. Try logging in with username + password
2. Try with email + password
3. See error

### Expected behavior
These credentials should work

### Screenshots/Screencasts
![lemmur-failed_login](https://user-images.githubusercontent.com/85603/105921882-5ce07080-5fee-11eb-87fc-906b1abfcf34.png)

### Additional context
I've tried both lemmur 0.1.1 and 0.2.0. Please let me know how I can debug this further, thanks!

**Comment by shilangyu** [comment]
Please double check if it doesn't work with lemmur 0.2.0. I say that because you got an empty error message and the lemmy.ml icon did not load, both indicating that API v1 is used

You can check the version in settings > About Lemmur

**Comment by michel-slm** [comment]
@shilangyu ok, I feel a bit silly now. Somehow trying to install the 0.2.0 APK over the 0.1.1 one always fails, and I did not notice that. It is indeed the API v1 issue -- the feed was also not working, and it's working on 0.2.0 even before I log in. Thanks!
