### ISSUE TITLE
Comments showing a gray block.

### ISSUE THREAD

**Issue by dessalines** [krawieck/lemmur#120]
### Device info

- OS: Android
- OS version: 10
- Device: Redmi Note 7

### Describe the bug

I get this on version `v0.2.0`:

![image](https://user-images.githubusercontent.com/930215/106170957-034b8380-615f-11eb-8112-158ebb99063e.png)

### Steps to reproduce

1. Click on any post, see this instead of comments.

**Comment by mikeyh30** [comment]
Device info

    OS: Ubuntu
    OS version: 20.10

I also see this bug in the linux version v0.2.0
