### ISSUE TITLE
Wrong comment link - 404

### ISSUE THREAD

**Issue by koalp** [krawieck/lemmur#127]
### Device info

- OS: android
- OS version: 10
- Device: xiaomi redmi note 5 pro

### Describe the bug

When sharing a comment or opening in browser, the link is wrong :
It should be <url>/post/<post_id>/comment/<comment_id> but the link generated is <url>/comment/<comment_id>

Currently generated link result in a 404 not found.

### Steps to reproduce

1. Go to any post with comments
2. Click on the three dot menu of a comment
3. Click on either "share" or "open in browser"
4. When using the link, there is a 404 not found

### Expected behavior

The generated URL should go to the comment

**Comment by dessalines** [comment]
I just tested this, seems to be working fine: https://lemmy.ml/post/51693/comment/32730

**Comment by krawieck** [comment]
thanks for letting us know, seems like apId doesn't always work as a reliable source of urls :/
