### ISSUE TITLE
Voting failed on the Windows build

### ISSUE THREAD

**Issue by pioneer** [krawieck/lemmur#135]
### Device info

- OS: Windows 10
- Device: HP EliteBook 850 G6

### App info:
- 0.2.2

### Description
On Windows 10, I'm constantly getting "Voting failed" when trying to vote against a post or comment. In fact, I've never been able to vote.

**Comment by shilangyu** [comment]
I am sadly unable to reproduce it, it works fine on my machine. I can think of two causes:

1. leftovers from a previous lemmur version: delete this folder `~\AppData\Roaming\com.example` and run lemmur again (this will log you out and remove all instances)
2. bug in flutter itself. Windows support is still in alpha so such weird behaviors might be happening

Does only voting not work? Perhaps some other actions fail too? Then it would be easier for me to pinpoint the problem

**Comment by pioneer** [comment]
I'll try to remove that folder and let you know, thanks.

**Comment by pioneer** [comment]
Removed the folder and the issue is gone, hence closing it.

**Comment by shilangyu** [comment]
I'm surprised this was the problem, we have not made any breaking changes to user settings (which are stored in this folder) since our first release :/ unless you perhaps built an early version a while back? Oh well. Glad it is solved

**Comment by pioneer** [comment]
@shilangyu That was a very early version indeed, maybe the first one published.
