### ISSUE TITLE
Links Do Not Work

### ISSUE THREAD

**Issue by FrankAlbella** [krawieck/lemmur#138]
### Device info

- OS: Android
- OS version: 11
- Device: Pixel 4a
- App version: 0.2.2

### Describe the bug
External links in posts or comments do not work. Links in posts do nothing, links in comments display a "couldn't open link, Exception" error message 

### Steps to reproduce

1. Open app
2. Find post linking to an external site 
3. Tap on the external site box
4. Nothing happens 
5. Find comment with link to an external site 
6. Tap on the link 
7. "couldn't open link, Exception" error message appears

### Expected behavior
Tapping on a link will open it in the [in app] browser

**Comment by shilangyu** [comment]
Could you tell me a specific post where you encounter this problem? Every post I try it works fine

**Comment by FrankAlbella** [comment]
> Could you tell me a specific post where you encounter this problem? Every post I try it works fine

It happens on every post. Check the video I've attached to this comment

https://user-images.githubusercontent.com/3748949/107123125-cb80c200-6869-11eb-8b04-c63ac5ca5c7b.mp4

**Comment by Bjorn99** [comment]
I am facing the same issue. The links just don't work!

**Comment by shilangyu** [comment]
This seems to be an android 11 issue, we sadly do not have access to a physical device with android 11, on an emulator everything works fine. So sadly this issue might take longer to fix than we would like

**Comment by Bjorn99** [comment]
You are right! The links work perfectly on android 10. I checked it on a Redmi device with android 10. Hope the problem with android 11 gets fixed soon.

**Comment by pioneer** [comment]
I can confirm this issue on my OnePlus 8 Pro with the latest Android 11. Though I've found a [link](https://lemmy.ml/post/52185) that opens, but that's the only one. The rest links either don/'t open silently or there's an exception like the described above.

**Comment by shilangyu** [comment]
Hey, could any of you try this apk: https://we.tl/t-dKrSIY1NGZ (on a phone with android 11). It seems android 11 introduced new permissions for link launching which we had not enabled.

**Comment by pioneer** [comment]
Works brilliantly! Haven't spotted any links that don't open, I was able to open everything.

**Comment by shilangyu** [comment]
Awesome, we will push a fix with the next release. We might also do the release earlier since this is a serious bug
