### ISSUE TITLE
Chapo.chat not recognized on instance list

### ISSUE THREAD

**Issue by protodrew** [krawieck/lemmur#141]
### Device info

- OS: android
- OS version: 11
- Device: samsung galaxy s20

### Describe the bug
When on the add an instance selection, inserting chapo.chat does not work.

**Comment by shilangyu** [comment]
Related to #113 (probably a duplicate), this is because chapo chat runs custom code, currently we only support pure lemmy instances

**Comment by krawieck** [comment]
chapo.chat still uses API v1, so we're gonna have to wait till they transition to v2
