### ISSUE TITLE
Comment button partly overlaps voting buttons

### ISSUE THREAD

**Issue by pioneer** [krawieck/lemmur#142]
Open any post and scroll to the very bottom. The comment button in the lower right corner covers a part of the voting arrow of the last comment. While I can still press that button, it'd be better to move the comment button a bit away from other inputs.
![Screenshot_20210208-192804.jpg](https://user-images.githubusercontent.com/200538/107258607-abf1c100-6a44-11eb-9f50-5ef5ee298dfa.jpg)

**Comment by krawieck** [comment]
That's odd, I thought we add enough padding to accommodate the button. I will look into that

**Comment by shilangyu** [comment]
> That's odd, I thought we add enough padding to accommodate the button. I will look into that

I already pushed a fix to my PR, wrong value was used
