### ISSUE TITLE
A new Flutter project instead of proper title on Windows

### ISSUE THREAD

**Issue by pioneer** [krawieck/lemmur#143]
On Windows, the app got frozen and Windows says "A new Flutter project is not responding". Seems a proper app name like "Lemmy" or "Lemmur" or maybe the instance name is not set for the Windows app.
![IMG_20210208_203137.jpg](https://user-images.githubusercontent.com/200538/107265607-258dad00-6a4d-11eb-956f-f997863f3fff.jpg)

**Comment by shilangyu** [comment]
Thanks, we have not modified windows metadata yet. While I'm at it I'll change the icon too
