### ISSUE TITLE
Duplicates in the feed

### ISSUE THREAD

**Issue by pioneer** [krawieck/lemmur#149]
I've just seen this in my feed, noting like that in the web UI.
![Screenshot_20210211-180211.jpg](https://user-images.githubusercontent.com/200538/107663086-a63dea80-6c93-11eb-96ab-9cb4933bf83e.jpg)

The APK I use is the one from issue #138.

**Comment by dessalines** [comment]
lemmy-ui does this on the front-end side: here's some code you could potentially use / convert to your needs. 

https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/post-listings.tsx#L62
