### ISSUE TITLE
Selectable text when replying to comments

### ISSUE THREAD

**Issue by shilangyu** [krawieck/lemmur#157]
### Is your feature request related to a problem? Please describe.

When replying to a comment it is common to want to copy the parent comment in order to quote it.

### Describe the solution you'd like

Be able to select comment's text

**Comment by fazlerabbi37** [comment]
sometime it is also helpful to be able to select the main content. could this be considered same as comment text?

**Comment by shilangyu** [comment]
Do you mean creating a top level comment to a post? (as opposed to replying to a comment)

**Comment by fazlerabbi37** [comment]
no I mean the main content of the post you are commenting. maybe I see something in the post that I want to copy but there is now way to select the text so no way to copy.

**Comment by shilangyu** [comment]
Oh, you're right, that should be an option as well. I'll open a separate issue for that

**Comment by fazlerabbi37** [comment]
thank you very much! @shilangyu. please do reference the new issue here. :heart:
