### ISSUE TITLE
Collapse/expand comments toggle

### ISSUE THREAD

**Issue by Victor239** [krawieck/lemmur#163]
A toggle which allows collapsing and expanding comments, including the parent comment of any thread.

**Comment by krawieck** [comment]
Have you tried long-pressing?

**Comment by Victor239** [comment]
Ah thanks that works. It's less discoverable than short-pressing which is the typical behaviour I've found on Reddit and Hacker News apps which I'd prefer. Or maybe a setting to pick one or the other?

**Comment by krawieck** [comment]
sure we can add that
