### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by illgetanewone** [krawieck/lemmur#168]
Since https://github.com/krawieck/lemmur/issues/138 got fixed recently it'd be awesome to get a new release with this fix in it.

I know not every fix deserves it's own release, but this is rather a big one.

Using a link aggregator is kinda pointless if you can't actually follow any links.

**Comment by shilangyu** [comment]
Sorry for the delay, just released a new version.

Hopefully it will soon appear on fdroid/play store. If not, you can download an APK from the github release tab
