### ISSUE TITLE
When voted from the main feed, the arrow isn't highlighted in the post

### ISSUE THREAD

**Issue by pioneer** [krawieck/lemmur#171]
Browse your main posts feed, vote for any post, then enter this post. You'll see your vote is taken into account and counted, but the voting arrow in the post isn't highlighted (see the video).

https://user-images.githubusercontent.com/200538/109296557-28ecab00-7839-11eb-8c4a-232c000dec7d.mp4

**Comment by shilangyu** [comment]
This should be straight forward to fix.

BTW: github now allows pasting mp4 files straight to the issue so you don't have to generate dropbox links

**Comment by pioneer** [comment]
Thanks, reuploaded the video here.

**Comment by shilangyu** [comment]
fixed in https://github.com/krawieck/lemmur/pull/261

**Comment by shilangyu** [comment]
> This should be straight forward to fix.

it was not :)
