### ISSUE TITLE
Account switcher not working

### ISSUE THREAD

**Issue by pipoprods** [krawieck/lemmur#182]
### Device info

- OS: Android 
- OS version: 9 (LineageOS 16)
- Device: Fairphone 3

### Describe the bug

Two accounts (same instance) configured on the device. Switching account from the accounts view doesn't update the account details (avatar, posts & comments lists), nor is the main feed (subscribed communities).

### Steps to reproduce

1. Open app
2. Go to "Accounts" tab (rightmost icon)
3. Switch account
4. The account details & main feed are the former account ones

### Expected behavior

The account details & main feed should be updated to match selected account.

### Additional context

Going to "Settings" → "Accounts" then longpressing an account makes the account switch (once).
The feed remains the former account one, its update has to be triggered manually to get it updated.

**Comment by shilangyu** [comment]
That's weird, this bug seems to exist almost much from the beginning, I'm surprised we have not noticed it. Thanks for reporting, I found the issue and I'm working on a fix
