### ISSUE TITLE
Support Lemmy API v3

### ISSUE THREAD

**Issue by dessalines** [krawieck/lemmur#189]
In ~1-2 weeks, lemmy will be moving to API v3, mainly due to migration of the `user_` to `person` table, meaning all of the user and user_id terms are changing in the API. Here's the diff with API v2:

https://github.com/LemmyNet/lemmy-js-client/pull/9/files

Let me know if there's any changes it makes sense for us to make.

**Comment by krawieck** [comment]
Thank's for letting us know!

There's one thing that would be good to see with saved posts/comments: ability to fetch content without fetching the full user details every time, also ability to select just one type of content to be fetched

**Comment by dessalines** [comment]
Could you open up an issue for that on lemmy. It would be very simple, just adding a `saved_only` field to `GetPosts` and `GetComments`.
