### ISSUE TITLE
F-Droid release update

### ISSUE THREAD

**Issue by illgetanewone** [krawieck/lemmur#192]
I'm late to the party since #168 cut the new release, but I just realized that it's been on google play for almost a month now, f-droid still hasn't picked up the new version.

I'm sadly not familiar with how it all works, but I imagine something is missing on lemmur's side for f-droid to automatically pick up new releases?

**Comment by shilangyu** [comment]
Yes there was an error on f-droids metadata file which I have reported. It was [fixed promptly](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8606). Looks like the new version got [built already](https://f-droid.org/wiki/index.php?title=com.krawieck.lemmur/lastbuild_12&redirect=no) but for some reason it is still not updated in f-droid. I sadly don't know the exact lifecycle of updates but I presume now we just wait for f-droid to refresh its repo with the new APK.

**Comment by illgetanewone** [comment]
it took it's time, but it finally arrived! :tada: 

thanks for the work!

**Comment by Anachron** [comment]
Sorry for bumping this, but the `0.4.0` release is still not on Fdroid. Same issue?

**Comment by shilangyu** [comment]
We have no control over f-droids build process, so new version of lemmur will appear on f-droid only once their build system has a new run, the time it takes is quite unpredictable so I sadly cannot tell you when it will appear in the f-droid store :/

**Comment by Anachron** [comment]
@shilangyu thank you for that very quick reply, I downloaded the version from the Play Store for now because the `0.3.0` version stopped working with the recent API changes.

**Comment by shilangyu** [comment]
I hate to say this but while Lemmy is unstable quick updates are very important thus I would probably recommend using github releases or the play store for now
