### ISSUE TITLE
Allow removing instances from Accounts view

### ISSUE THREAD

**Issue by Porrumentzio** [krawieck/lemmur#193]
### Is your feature request related to a problem? 
Having added some instances to see specific post, now it's not possible to remove unwanted instances.

### Describe the solution you'd like
I propose adding a button at the right side of each instance on Accounts view.

### Describe alternatives you've considered
Having such option(s) on tap or long press instance name on Accounts view.

**Comment by shilangyu** [comment]
Ok, I take this as a "please redesign the deletion process". Its the 4th time someone requests it when in fact it already is implemented: swipe the instance to the left in the accounts view to reveal the delete button

So therefore we will change it to make it more obvious
