### ISSUE TITLE
lemmur 0.4.x will not install

### ISSUE THREAD

**Issue by testman42** [krawieck/lemmur#199]
- OS: Lineage OS
- OS version: 18.1
- Device: Xiaomi Mi A2 Lite

The .apk (arm64-v8a) will not install, always results in "App not installed" message.
Tried armeabi-v7a as well, same result.
Happens for both 0.4.0 and 0.4.1

I already have Lemmur 0.3.0 installed from F-Droid. Installation of that worked fine.

Will try to dig deeper into this, to provide more information.

**Comment by shilangyu** [comment]
I don't know if it a problem or our side or just the way android works. But to fix it you need to uninstall your previous version first and then install a new one (this happens when you try to install from different sources)

**Comment by testman42** [comment]
Yep, deleting previous one and installing 0.4.1 worked.
Thank you :+1:
