### ISSUE TITLE
Feed not loading

### ISSUE THREAD

**Issue by smufa** [krawieck/lemmur#204]
### Device info
Android all tested devices

### Describe the bug
Feed keeps loading but never loads, and on the second page it only says LemmyApiException:

### Steps to reproduce

1. Open app
2. See problem

### Expected behavior
It should load my feed.

**Comment by krawieck** [comment]
What version of the app? (Go to settings -> about lemmur)

**Comment by smufa** [comment]
0.3.0 is the one on fdroid behind?

**Comment by krawieck** [comment]
Seems like it. It's an old version. Lemmy changed their api so now it's not working with that version

**Comment by smufa** [comment]
ok thanks :)

**Comment by shilangyu** [comment]
For more info check https://github.com/krawieck/lemmur#app-not-installed---what-to-do
