### ISSUE TITLE
Profile Tab shows some one else's profile

### ISSUE THREAD

**Issue by Yohe-Am** [krawieck/lemmur#207]
### Device info

- OS: Android 
- OS version: 8.0
- Device: LG H918

### Describe the bug
The profile tab shows profile details of another user. It's always the same user. Restarting the app doesn't make this go away. 

### Steps to reproduce

1. Go to the Profile Rab

### Expected behavior
To show me details of my profile. 

### Screenshots/Screencasts
[Screen in matrix chat](https://matrix.to/#/!BZVTUuEiNmRcbFeLeI:matrix.org/$1618085361115903OIeLg:matrix.org?via=matrix.org&via=privacytools.io&via=tchncs.de)

### Additional context
I'm on version 4.1.0. And if iirc, it was showing me my own profile properly for the first few minutes with the app.

**Comment by shilangyu** [comment]
Thanks for opening an issue about it. I already found the cause but it will be more annoying to fix than I anticipated...
