### ISSUE TITLE
Accounts removed on update

### ISSUE THREAD

**Issue by thelegendofbrian** [krawieck/lemmur#211]
### Device info

- OS: Android
- OS version: 10
- Device: Moto g power

### Describe the bug
Upon updating the app using Google Play, previously added accounts are removed.

### Steps to reproduce

1. Add an account to lemmur
2. Manually update the app from the Google Play store or automatically let it update
3. Open the updated app
4. Notice no accounts are listed

### Expected behavior
User accounts should be preserved between updates. They should not need to be readded.

**Comment by krawieck** [comment]
This was intended behavior. Look at the change log. We kinda fucked up and we had to fix the way accounts are handled
