### ISSUE TITLE
Lemmy new release breaking changes.  App will not work, no matter what

### ISSUE THREAD

**Issue by cud4m** [krawieck/lemmur#225]
### Device info

- OS:  Android
- OS version: 10/11
- Device: Nexus 6/ Xiaomi Redmi Note S 9 
### Describe the bug
Lemmy new release causing lemmy_api package to break, those causing Lemmur to break.
API has been change  creator_id field  removed from  API.
Lemmy release info:
https://github.com/LemmyNet/lemmy/blob/main/RELEASES.md

Lemmy API changes: 
https://github.com/LemmyNet/lemmy-js-client/compare/0.10.0...0.11.0-rc.13
Commit 1e60699 root cause of the problem.

### Steps to reproduce

1. Open the app
2. Connect to any server with new Lemmy release
3. Any view trying to render a post will not work

### Screenshots/Screencasts
![lemmynotworking](https://user-images.githubusercontent.com/22178259/116401298-5f3faa00-a82b-11eb-98bf-e95d4752c90d.jpg)

### Additional context
JSON parse will fail.
lemmy_api_client-0.14.0/lib/src/v3/models/source.g.dart line 461

Guess I'll report it at lemmy_api_client repo too. I thought of creating a pull request  with the fix, but the lemmy_api_client has a new release, breaking a lot of things. And there's only one branch so, cannot make a pull request to previous release...

**Comment by shilangyu** [comment]
Thanks, I already added lemmy v0.11.0 support yesterday: https://github.com/krawieck/lemmur/tree/lemmy-0.11.0

It's in the PR queue, should be merged today

**Comment by cud4m** [comment]
Oh, didn't realize that. My bad.  Guess we can close it then.
