### ISSUE TITLE
Doesn't load any content

### ISSUE THREAD

**Issue by bstaxt** [krawieck/lemmur#227]
### Device info

- OS: Android
- OS version: 10
- Device: OnePlus 2

### Describe the bug
No posts load regardless of filters selected. Loading wheel stays up indefinitely.

### Steps to reproduce

1. Open app
2. Try to see any posts

### Expected behavior
Posts automatically load on home screen. No preference if this is for 'All' or 'Subscribed'

### Screenshots/Screencasts
N/A

### Additional context
N/A

**Comment by shilangyu** [comment]
What version of lemmur are you running?

**Comment by ljrk0** [comment]
Same on 0.4.2 which unfortunately is the current version distributed on F-Droid.

**Comment by shilangyu** [comment]
Lemmur was updated to v0.5.0 to support lemmy v0.11.0, please see [FAQ](https://github.com/krawieck/lemmur#version-xxx-was-released-why-is-it-not-yet-on-f-droid)

@bstaxt please confirm whether you are also on 0.4.2

**Comment by ljrk0** [comment]
Yep, unfortunately the F-Droid build seems to use a different signature (?) and they aren't compatible (can't be used for upgrades).  I also suspect the original report is using an old version and the issue needs to be fixed elsewhere.

**Comment by shilangyu** [comment]
> the issue needs to be fixed elsewhere

It's a non-issue, we just need to be patient and let f-droid pick up the new version (might take even a full week). This "critical update" issue happens pretty much on every update because lemmy is unstable and breaks stuff often. You might want to use github release apks or the play store to get quick updates for the near future, or just wait for f-droid

**Comment by ljrk0** [comment]
Without derailing, I think one can see that as a user experience issue.  Of course, it's unstable and as such will eventually be addressed, but F-Droid is notorious for late updates (lacking server capacity, so everyone please contribute!) which is another problem... to be solved elsewhere.  Ideally, F-Droid doesn't have much of a lag here.

**Comment by bstaxt** [comment]
Thanks for all the replies. To confirm, I am using 0.4.2. It happened once on an old update transition too and I thought I remembered that this was listed in 'bug fixes', so I thought it might've been helpful to you to hear about. Sorry for stirring the pot on an external issue. I will be patient with F-Droid rollouts on future releases and check against new releases on git. Thanks again for your work.
