### ISSUE TITLE
Rich text/WYSIWYG editor

### ISSUE THREAD

**Issue by trymeouteh** [krawieck/lemmur#236]
A WYSIWYG editor for posts and comments

**Comment by krawieck** [comment]
We do not currently have plans to make a WYSIWYG editor. But we want to add buttons for inserting markdown things, such as bold, italics, links and lemmy specific stuff such as mentioning another user

**Comment by shilangyu** [comment]
Since we don't want to have a WYSIWYG editor, we are closing it in favor of a task of enriching the markdown editor.
