### ISSUE TITLE
Ask for confirmation when discarding post or comment

### ISSUE THREAD

**Issue by gallrein** [krawieck/lemmur#255]
Currently, if one accidentally navigates back while writing a post or comment, the create post page is immediately closed and the written text is lost.

A possible solution to prevent this annoyance would be to display a dialog asking the user if they want to discard the draft when they navigate back (or press the close button) and the text field is not empty.

**Comment by shilangyu** [comment]
Since we want to have drafts, we want to avoid any confirmation dialogs. Closing in favor of #262
