### ISSUE TITLE
LemmyApiException: password_incorrect

### ISSUE THREAD

**Issue by PandaCoderPL** [krawieck/lemmur#259]
### Device info

- OS: GrapheneOS
- OS version: sunfish-factory-2021092220 (Android 11)
- Device: Google Pixel 4a
- Lemmur version: v0.6.0

### Describe the bug

When I'm trying to log into my account I'm getting "LemmyApiException: password_incorrect".

### Steps to reproduce

1. Try to log into your account.
2. See error.

### Relevant logs

I'm not able to provide any logs related to this issue.

### Expected behavior

I should be able to successfully log into my account.

### Screenshots/Screencasts

I'm not able to provide any screenshots of the issue but in my opinion I provided enough details about the issue when describing the bug.

### Additional context

I'm sure that password is correct because it was copied and pasted from password manager and everything works fine through the website. I'm also sure that I'm using correct instance.
My issue seems to be duplicate of #233 where @rikmeijer wrote that issue seems fixed in newest version but unfortunarely issue still persists for me.

**Comment by krawieck** [comment]
That's an odd issue, we'll try to find the problem. In the meantime I'll ask you some questions that could lead us to where the issue lies:

- Does your password contain characters outside of the [ASCII range](https://www.asciitable.com/)?
- Is your password longer than 60 characters?

**Comment by PandaCoderPL** [comment]
> That's an odd issue, we'll try to find the problem. In the meantime I'll ask you some questions that could lead us to where the issue lies:

Good luck fixing the issue.
>     * Does your password contain characters outside of the [ASCII range](https://www.asciitable.com/)?
No
>     * Is your password longer than 60 characters?
Yes

**Comment by dessalines** [comment]
The backend on upcoming version will do a length check: https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/lib.rs#L456

**Comment by krawieck** [comment]
> >     * Is your password longer than 60 characters?
> 
> Yes

Ok, so we found the problem

![image](https://user-images.githubusercontent.com/10037914/135046330-1f4af058-db22-463c-88f0-9731d9335bc1.jpeg)

**Comment by shilangyu** [comment]
As a temporary workaround you can login to lemmur by entering only the first 60chars of your password (this is what is happening on lemmy-ui and is why it works there)

**Comment by PandaCoderPL** [comment]
> As a temporary workaround you can login to lemmur by entering only the first 60chars of your password (this is what is happening on lemmy-ui and is why it works there)

It works great now, thank you.
