### ISSUE TITLE
Add pull to refresh

### ISSUE THREAD

**Issue by shilangyu** [krawieck/lemmur#66]
### Is your feature request related to a problem? Please describe.

Currently there is no way to refresh contents of a page. The only solution is to exit and go back to the page.

### Describe the solution you'd like

A pull to refresh on appropriate pages

- [ ] ... (insert list of pages that should have it)

**Comment by maplerichie** [comment]
I can do this

FYI
https://hacktoberfest.digitalocean.com/hacktoberfest-update all PR with label "hacktoberfest-accepted" only counted
