### ISSUE TITLE
Truncate long text posts

### ISSUE THREAD

**Issue by krawieck** [krawieck/lemmur#84]
### Is your feature request related to a problem? Please describe.
Text posts can be very long, and that can be annoying is user is not interested in its contents.

### Describe the solution you'd like
truncate the post. if using lines it should be at ~~20~~ 10 lines (it could also be length in pixels roughly equivalent to ~~20~~ 10 lines)
to indicate that there's more the last 2 to 4 lines should have gradual fade applied to them

mockup:
![Screenshot_20201109-114932 copy](https://user-images.githubusercontent.com/10037914/98538302-d3d95900-228a-11eb-883d-df4a43000b21.jpg)

**Comment by ryg-git** [comment]
If it is ok I would like to take up this issue

**Comment by shilangyu** [comment]
Sure, assigned it to you. If you have any questions or need help with this do not hesitate to contact us
